
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef JSONTEST_H
#define JSONTEST_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 jsontest_valueRangeTest (UNS8 typeValue, void * value);
const indextable * jsontest_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data jsontest_Data;
extern UNS8 VAR;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER8 ARRAY[2];		/* Mapped at index 0x2001, subindex 0x01 - 0x02 */
extern UNS8 RECORD_RECORD_1;		/* Mapped at index 0x2002, subindex 0x01 */
extern INTEGER16 RECORD_RECORD_2;		/* Mapped at index 0x2002, subindex 0x02 */
extern UNS8 Global_Interrupt_Enable_Digital_Sure;		/* Mapped at index 0x6000, subindex 0x00*/
extern INTEGER32 RECORD_Software_position_limit_Minimal_position_limit;		/* Mapped at index 0x6100, subindex 0x01 */
extern INTEGER32 RECORD_Software_position_limit_Maximal_position_limit;		/* Mapped at index 0x6100, subindex 0x02 */
extern INTEGER16 RECORD_AL_Action_AL_1_Action_1;		/* Mapped at index 0x6180, subindex 0x01 */
extern INTEGER16 RECORD_AL_Action_AL_1_Action_2;		/* Mapped at index 0x6180, subindex 0x02 */
extern INTEGER16 RECORD_AL_Action_AL_1_Action_3;		/* Mapped at index 0x6180, subindex 0x03 */
extern INTEGER16 RECORD_AL_Action_AL_1_Action_4;		/* Mapped at index 0x6180, subindex 0x04 */
extern INTEGER16 RECORD_AL_Action_AL_1_Action_5;		/* Mapped at index 0x6180, subindex 0x05 */
extern INTEGER16 RECORD_AL_Action_AL_1_Action_6;		/* Mapped at index 0x6180, subindex 0x06 */
extern INTEGER16 ARRAY_Acceleration_Value[2];		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */
extern UNS32 Device_Type_1_and_0;		/* Mapped at index 0x6300, subindex 0x00*/
extern UNS32 Device_Type_2_and_0;		/* Mapped at index 0x6302, subindex 0x00*/
extern INTEGER32 NARRAY_CAM1_Low_Limit[2];		/* Mapped at index 0x6400, subindex 0x01 - 0x02 */
extern INTEGER32 NARRAY_CAM2_Low_Limit[0];		/* Mapped at index 0x6402, subindex 0x01 - 0x00 */
extern UNS32 NRECORD_Receive_PDO_1_Parameter_COB_ID_used_by_PDO;		/* Mapped at index 0x6500, subindex 0x01 */
extern UNS8 NRECORD_Receive_PDO_1_Parameter_Transmission_Type;		/* Mapped at index 0x6500, subindex 0x02 */
extern UNS16 NRECORD_Receive_PDO_1_Parameter_Inhibit_Time;		/* Mapped at index 0x6500, subindex 0x03 */
extern UNS8 NRECORD_Receive_PDO_1_Parameter_Compatibility_Entry;		/* Mapped at index 0x6500, subindex 0x04 */
extern UNS16 NRECORD_Receive_PDO_1_Parameter_Event_Timer;		/* Mapped at index 0x6500, subindex 0x05 */
extern UNS8 NRECORD_Receive_PDO_1_Parameter_SYNC_start_value;		/* Mapped at index 0x6500, subindex 0x06 */
extern UNS32 NRECORD_AL_1_Action_AL_1_Action_1;		/* Mapped at index 0x6580, subindex 0x01 */
extern UNS32 NRECORD_AL_1_Action_AL_1_Action_2;		/* Mapped at index 0x6580, subindex 0x02 */
extern UNS32 NRECORD_AL_1_Action_AL_1_Action_3;		/* Mapped at index 0x6580, subindex 0x03 */
extern UNS32 NRECORD_AL_1_Action_AL_1_Action_4;		/* Mapped at index 0x6580, subindex 0x04 */
extern UNS32 NRECORD_AL_1_Action_AL_1_Action_5;		/* Mapped at index 0x6580, subindex 0x05 */
extern UNS32 NRECORD_AL_1_Action_AL_1_Action_6;		/* Mapped at index 0x6580, subindex 0x06 */
extern UNS16 Producer_Heartbeat_Time;		/* Mapped at index 0x6600, subindex 0x00*/

#endif // JSONTEST_H
