
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef JSONTEST_LEGACY_OBJECTDEFINES_H
#define JSONTEST_LEGACY_OBJECTDEFINES_H

/*
    Object defines naming convention:
    General:
        * All characters in object names that does not match [a-zA-Z0-9_] will be replaced by '_'.
        * Case of object dictionary names will be kept as is.
    Index : Node object dictionary name +_+ index name +_+ Idx
    SubIndex : Node object dictionary name +_+ index name +_+ subIndex name +_+ sIdx
*/

#define jsontest_Device_Type_Idx 0x1000
#define jsontest_Device_Type_Device_Type_sIdx 0x00    /* Device type

#define jsontest_Error_Register_Idx 0x1001
#define jsontest_Error_Register_Error_Register_sIdx 0x00    /* Err register

#define jsontest_Identity_Idx 0x1018
#define jsontest_Identity_Number_of_Entries_sIdx 0x00    /* R0
#define jsontest_Identity_Vendor_ID_sIdx 0x01    /* R1
#define jsontest_Identity_Product_Code_sIdx 0x02    /* R2
#define jsontest_Identity_Revision_Number_sIdx 0x03    /* R3
#define jsontest_Identity_Serial_Number_sIdx 0x04    /* R4

#define jsontest_Client_SDO_1_Parameter_Idx 0x1280
#define jsontest_Client_SDO_1_Parameter_Number_of_Entries_sIdx 0x00    /* SDO0
#define jsontest_Client_SDO_1_Parameter_COB_ID_Client_to_Server__Transmit_SDO__sIdx 0x01    /* SDO1
#define jsontest_Client_SDO_1_Parameter_COB_ID_Server_to_Client__Receive_SDO__sIdx 0x02    /* SDO2
#define jsontest_Client_SDO_1_Parameter_Node_ID_of_the_SDO_Server_sIdx 0x03    /* SDO3

#define jsontest_Client_SDO_2_Parameter_Idx 0x1281
#define jsontest_Client_SDO_2_Parameter_Number_of_Entries_sIdx 0x00    /* client0
#define jsontest_Client_SDO_2_Parameter_COB_ID_Client_to_Server__Transmit_SDO__sIdx 0x01    /* client1
#define jsontest_Client_SDO_2_Parameter_COB_ID_Server_to_Client__Receive_SDO__sIdx 0x02    /* client2
#define jsontest_Client_SDO_2_Parameter_Node_ID_of_the_SDO_Server_sIdx 0x03    /* client3

#define jsontest_Client_SDO_3_Parameter_Idx 0x1282
#define jsontest_Client_SDO_3_Parameter_Number_of_Entries_sIdx 0x00
#define jsontest_Client_SDO_3_Parameter_COB_ID_Client_to_Server__Transmit_SDO__sIdx 0x01
#define jsontest_Client_SDO_3_Parameter_COB_ID_Server_to_Client__Receive_SDO__sIdx 0x02
#define jsontest_Client_SDO_3_Parameter_Node_ID_of_the_SDO_Server_sIdx 0x03

#define jsontest_Receive_PDO_1_Parameter_Idx 0x1400
#define jsontest_Receive_PDO_1_Parameter_Highest_SubIndex_Supported_sIdx 0x00    /* rpdo0
#define jsontest_Receive_PDO_1_Parameter_COB_ID_used_by_PDO_sIdx 0x01    /* rpdo1
#define jsontest_Receive_PDO_1_Parameter_Transmission_Type_sIdx 0x02    /* rpdo2
#define jsontest_Receive_PDO_1_Parameter_Inhibit_Time_sIdx 0x03    /* rpdo3
#define jsontest_Receive_PDO_1_Parameter_Compatibility_Entry_sIdx 0x04    /* rpdo4
#define jsontest_Receive_PDO_1_Parameter_Event_Timer_sIdx 0x05    /* rpdo5
#define jsontest_Receive_PDO_1_Parameter_SYNC_start_value_sIdx 0x06    /* rpdo6

#define jsontest_Receive_PDO_2_Parameter_Idx 0x1401
#define jsontest_Receive_PDO_2_Parameter_Highest_SubIndex_Supported_sIdx 0x00    /* c0
#define jsontest_Receive_PDO_2_Parameter_COB_ID_used_by_PDO_sIdx 0x01    /* c1
#define jsontest_Receive_PDO_2_Parameter_Transmission_Type_sIdx 0x02    /* c2
#define jsontest_Receive_PDO_2_Parameter_Inhibit_Time_sIdx 0x03    /* c3
#define jsontest_Receive_PDO_2_Parameter_Compatibility_Entry_sIdx 0x04    /* c4
#define jsontest_Receive_PDO_2_Parameter_Event_Timer_sIdx 0x05    /* c5
#define jsontest_Receive_PDO_2_Parameter_SYNC_start_value_sIdx 0x06    /* c6

#define jsontest_Receive_PDO_3_Parameter_Idx 0x1402
#define jsontest_Receive_PDO_3_Parameter_Highest_SubIndex_Supported_sIdx 0x00
#define jsontest_Receive_PDO_3_Parameter_COB_ID_used_by_PDO_sIdx 0x01
#define jsontest_Receive_PDO_3_Parameter_Transmission_Type_sIdx 0x02
#define jsontest_Receive_PDO_3_Parameter_Inhibit_Time_sIdx 0x03
#define jsontest_Receive_PDO_3_Parameter_Compatibility_Entry_sIdx 0x04
#define jsontest_Receive_PDO_3_Parameter_Event_Timer_sIdx 0x05
#define jsontest_Receive_PDO_3_Parameter_SYNC_start_value_sIdx 0x06

#define jsontest_Receive_PDO_1_Mapping_Idx 0x1600
#define jsontest_Receive_PDO_1_Mapping_Number_of_Entries_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_Receive_PDO_2_Mapping_Idx 0x1601
#define jsontest_Receive_PDO_2_Mapping_Number_of_Entries_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_Receive_PDO_3_Mapping_Idx 0x1602
#define jsontest_Receive_PDO_3_Mapping_Number_of_Entries_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_Store_DCF_Idx 0x1f20
#define jsontest_Store_DCF_Number_of_Entries_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_VAR_Idx 0x2000
#define jsontest_VAR_VAR_sIdx 0x00    /* VAR

#define jsontest_ARRAY_Idx 0x2001
#define jsontest_ARRAY_Number_of_Entries_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_RECORD_Idx 0x2002
#define jsontest_RECORD_Number_of_Entries_sIdx 0x00    /* R0
#define jsontest_RECORD_RECORD_1_sIdx 0x01    /* R1
#define jsontest_RECORD_RECORD_2_sIdx 0x02    /* R2

#define jsontest_VAR__Global_Interrupt_Enable_Digital_Idx 0x6000
#define jsontest_VAR__Global_Interrupt_Enable_Digital_Global_Interrupt_Enable_Digital_Sure_sIdx 0x00    /* Nope

#define jsontest_RECORD__Software_position_limit_Idx 0x6100
#define jsontest_RECORD__Software_position_limit_Number_of_things_sIdx 0x00    /* Rec0
#define jsontest_RECORD__Software_position_limit_Minimal_position_limit_sIdx 0x01    /* Rec1
#define jsontest_RECORD__Software_position_limit_Maximal_position_limit_sIdx 0x02    /* Rec2

#define jsontest_RECORD__AL_Action_Idx 0x6180
#define jsontest_RECORD__AL_Action_Number_of_subs_sIdx 0x00    /* r0
#define jsontest_RECORD__AL_Action_AL_1_Action_1_sIdx 0x01    /* r1
#define jsontest_RECORD__AL_Action_AL_1_Action_2_sIdx 0x02    /* r2
#define jsontest_RECORD__AL_Action_AL_1_Action_3_sIdx 0x03    /* r3
#define jsontest_RECORD__AL_Action_AL_1_Action_4_sIdx 0x04    /* r4
#define jsontest_RECORD__AL_Action_AL_1_Action_5_sIdx 0x05    /* r5
#define jsontest_RECORD__AL_Action_AL_1_Action_6_sIdx 0x06    /* r6

#define jsontest_ARRAY__Acceleration_Value_Idx 0x6200
#define jsontest_ARRAY__Acceleration_Value_Number_of_Available_Channels_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_NVAR__Test_profile_1_Idx 0x6300
#define jsontest_NVAR__Test_profile_1_Device_Type_1_and_0_sIdx 0x00    /* dt10

#define jsontest_NVAR__Test_profile_2_Idx 0x6302
#define jsontest_NVAR__Test_profile_2_Device_Type_2_and_0_sIdx 0x00

#define jsontest_NARRAY__CAM1_Low_Limit_Idx 0x6400
#define jsontest_NARRAY__CAM1_Low_Limit_Number_of_Available_Channels_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_NARRAY__CAM2_Low_Limit_Idx 0x6402
#define jsontest_NARRAY__CAM2_Low_Limit_Number_of_Available_Channels_sIdx 0x00
/* subindex define not generated for array objects */

#define jsontest_NRECORD__Receive_PDO_1_Parameter_Idx 0x6500
#define jsontest_NRECORD__Receive_PDO_1_Parameter_Highest_SubIndex_Supported_sIdx 0x00    /* nr0
#define jsontest_NRECORD__Receive_PDO_1_Parameter_COB_ID_used_by_PDO_sIdx 0x01    /* nr1
#define jsontest_NRECORD__Receive_PDO_1_Parameter_Transmission_Type_sIdx 0x02    /* nr2
#define jsontest_NRECORD__Receive_PDO_1_Parameter_Inhibit_Time_sIdx 0x03    /* nr3
#define jsontest_NRECORD__Receive_PDO_1_Parameter_Compatibility_Entry_sIdx 0x04    /* nr4
#define jsontest_NRECORD__Receive_PDO_1_Parameter_Event_Timer_sIdx 0x05    /* nr5
#define jsontest_NRECORD__Receive_PDO_1_Parameter_SYNC_start_value_sIdx 0x06    /* nr6

#define jsontest_NRECORD__Receive_PDO_2_Parameter_Idx 0x6502
#define jsontest_NRECORD__Receive_PDO_2_Parameter_Highest_SubIndex_Supported_sIdx 0x00

#define jsontest_NRECORD__AL_1_Action_Idx 0x6580
#define jsontest_NRECORD__AL_1_Action_Number_of_Actions_sIdx 0x00    /* com0
#define jsontest_NRECORD__AL_1_Action_AL_1_Action_1_sIdx 0x01    /* com1
#define jsontest_NRECORD__AL_1_Action_AL_1_Action_2_sIdx 0x02    /* com2
#define jsontest_NRECORD__AL_1_Action_AL_1_Action_3_sIdx 0x03    /* com3
#define jsontest_NRECORD__AL_1_Action_AL_1_Action_4_sIdx 0x04    /* com4
#define jsontest_NRECORD__AL_1_Action_AL_1_Action_5_sIdx 0x05    /* com5
#define jsontest_NRECORD__AL_1_Action_AL_1_Action_6_sIdx 0x06    /* com6

#define jsontest_Producer_Heartbeat_Time_Idx 0x6600
#define jsontest_Producer_Heartbeat_Time_Producer_Heartbeat_Time_sIdx 0x00    /* Comment for it

#endif /* JSONTEST_LEGACY_OBJECTDEFINES_H */
