
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_LEGACY_H
#define MASTER_LEGACY_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Master_Data;

#endif // MASTER_LEGACY_H
