
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MINIMAL_H
#define MINIMAL_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Null_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Null_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Null_Data;

#endif // MINIMAL_H
