
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MINIMAL_LEGACY_H
#define MINIMAL_LEGACY_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Null_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Null_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Null_Data;

#endif // MINIMAL_LEGACY_H
