
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVE_LEGACY_H
#define SLAVE_LEGACY_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Slave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Slave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Slave_Data;

#endif // SLAVE_LEGACY_H
