
/* File generated by gen_cfile.py. Should not be modified. */

#include "slave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Slave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Slave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Slave_iam_a_slave = 1;

TIMER_HANDLE Slave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Slave_obj1000 = 0x0;	/* 0 */
                    subindex Slave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Slave_obj1001 = 0x0;	/* 0 */
                    subindex Slave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Slave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Slave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Slave_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Slave_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 Slave_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Slave_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Slave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Slave_highestSubIndex_obj1016 = 0;
                    UNS32 Slave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Slave_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Slave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Slave_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Slave_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Slave_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Slave_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Slave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Slave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Slave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 Slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex Slave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 Slave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 Slave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 Slave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 Slave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1601[7], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1602[7], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1603[7], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 Slave_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 Slave_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 Slave_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Slave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Slave_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 Slave_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A00[7], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A01[7], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A02[7], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Slave_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 Slave_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave_obj1A03[7], NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Slave_objdict[] = 
{
  { (subindex*)Slave_Index1000,sizeof(Slave_Index1000)/sizeof(Slave_Index1000[0]), 0x1000},
  { (subindex*)Slave_Index1001,sizeof(Slave_Index1001)/sizeof(Slave_Index1001[0]), 0x1001},
  { (subindex*)Slave_Index1018,sizeof(Slave_Index1018)/sizeof(Slave_Index1018[0]), 0x1018},
  { (subindex*)Slave_Index1200,sizeof(Slave_Index1200)/sizeof(Slave_Index1200[0]), 0x1200},
  { (subindex*)Slave_Index1400,sizeof(Slave_Index1400)/sizeof(Slave_Index1400[0]), 0x1400},
  { (subindex*)Slave_Index1401,sizeof(Slave_Index1401)/sizeof(Slave_Index1401[0]), 0x1401},
  { (subindex*)Slave_Index1402,sizeof(Slave_Index1402)/sizeof(Slave_Index1402[0]), 0x1402},
  { (subindex*)Slave_Index1403,sizeof(Slave_Index1403)/sizeof(Slave_Index1403[0]), 0x1403},
  { (subindex*)Slave_Index1600,sizeof(Slave_Index1600)/sizeof(Slave_Index1600[0]), 0x1600},
  { (subindex*)Slave_Index1601,sizeof(Slave_Index1601)/sizeof(Slave_Index1601[0]), 0x1601},
  { (subindex*)Slave_Index1602,sizeof(Slave_Index1602)/sizeof(Slave_Index1602[0]), 0x1602},
  { (subindex*)Slave_Index1603,sizeof(Slave_Index1603)/sizeof(Slave_Index1603[0]), 0x1603},
  { (subindex*)Slave_Index1800,sizeof(Slave_Index1800)/sizeof(Slave_Index1800[0]), 0x1800},
  { (subindex*)Slave_Index1801,sizeof(Slave_Index1801)/sizeof(Slave_Index1801[0]), 0x1801},
  { (subindex*)Slave_Index1802,sizeof(Slave_Index1802)/sizeof(Slave_Index1802[0]), 0x1802},
  { (subindex*)Slave_Index1803,sizeof(Slave_Index1803)/sizeof(Slave_Index1803[0]), 0x1803},
  { (subindex*)Slave_Index1A00,sizeof(Slave_Index1A00)/sizeof(Slave_Index1A00[0]), 0x1A00},
  { (subindex*)Slave_Index1A01,sizeof(Slave_Index1A01)/sizeof(Slave_Index1A01[0]), 0x1A01},
  { (subindex*)Slave_Index1A02,sizeof(Slave_Index1A02)/sizeof(Slave_Index1A02[0]), 0x1A02},
  { (subindex*)Slave_Index1A03,sizeof(Slave_Index1A03)/sizeof(Slave_Index1A03[0]), 0x1A03},
};

const indextable * Slave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
    int i;
    (void)d; /* unused parameter */
    switch(wIndex){
       case 0x1000: i = 0;break;
       case 0x1001: i = 1;break;
       case 0x1018: i = 2;break;
       case 0x1200: i = 3;break;
       case 0x1400: i = 4;break;
       case 0x1401: i = 5;break;
       case 0x1402: i = 6;break;
       case 0x1403: i = 7;break;
       case 0x1600: i = 8;break;
       case 0x1601: i = 9;break;
       case 0x1602: i = 10;break;
       case 0x1603: i = 11;break;
       case 0x1800: i = 12;break;
       case 0x1801: i = 13;break;
       case 0x1802: i = 14;break;
       case 0x1803: i = 15;break;
       case 0x1A00: i = 16;break;
       case 0x1A01: i = 17;break;
       case 0x1A02: i = 18;break;
       case 0x1A03: i = 19;break;
       default:
            *errorCode = OD_NO_SUCH_OBJECT;
            return NULL;
    }
    *errorCode = OD_SUCCESSFUL;
    return &Slave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Slave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Slave_firstIndex = {
  3, /* SDO_SVR */
  0, /* SDO_CLT */
  4, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  12, /* PDO_TRS */
  16 /* PDO_TRS_MAP */
};

const quick_index Slave_lastIndex = {
  3, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  19 /* PDO_TRS_MAP */
};

const UNS16 Slave_ObjdictSize = sizeof(Slave_objdict)/sizeof(Slave_objdict[0]); 

CO_Data Slave_Data = CANOPEN_NODE_DATA_INITIALIZER(Slave);

